[Adblock Plus 1.1]
! Version: 20210609
! Title: mylist
menhyil
cnql
sxybjjz
vh269
smfsjx
xhhou
fenniao
shenzhouc
yayjd
jinpu5
apexlathe
klsadm
pstatp
shsb88
bl686
900788
fafa004
xintengai
sqkcjg
zsjiahe
erqimall
mmstat
koudaiy
tkshyp
duoketuan
ghosttty
70url
zhiyingwang
yueduyy
roeey
ltwsh
kua8s
flipf
imooho
koudai
zkwpr
hnjyrc
py69
xiwnu
5weini
baiduvip
yunsen
ae01.alicdn
cbu01.alicdn
img.alicdn
winfisc
zao86789
zxvsuw
xi0021
mglvqian
hm.baidu.com
qdhhsnz
zpgjz
lsdys
fccxp
youle55
dsgy521
youhuomeishi
ynjk
hbwcl
heygugu
818tu
how5
configx
webofxm
srdoudizhu
haizirv
haofengsuye
lkflw
bxlsl
wanmancn
hmcvs.cn
4r3z2ahp8
umm6.cn
hzblic
lwinl
wangketuan
xyxy
ysyspb
jdcbuy
cnzz.com
maziyou
laiduobao
haohaizi
qcwzx
jianduankm
lovelala
muduli
qhuade
ntjacb
lanhouhou
feipukeplus
hsq3z.com
huanqiucaizhi
hnhgw.cn
sufficient.cn
jscsd
wgewj
sysapr
xkhejx
haoxiehui
8000zq
uplusbrand
yuyue
wsf-gz
cdxzx-tech
lotusland
gangaotong
blockplus.cc
mengmob
xdzlaser
hbb123
pwrt.pw
juseyx
weiceton
shnhnjn
kuxuan.pw
urI6.com
2008612.com
dema1905
wanmancn
guangyaoli
apple.com
7656c4.com
michael31lin.com
tetiao9.com
liuchengming.com
govjiangsu.cn
govhangzhou.cn
govzhuhai.cn
govgaungzhou.cn
xiuxiuji.com
cxcyhr.com
sc01.alicdn.com
byteimg.com
ppslsa.com
kowqd1.top
oceanbot-steam.com
googletagmanager.com
shiinaliu.com
tzsjwy.com
just-machinery
api.share.baidu.com
nsclick.baidu.com
push.zhanzhang.baidu.com
caishuitonghr.com
qqppz.com
anlgh.com
mmstat.com
realwanghao.com
zzdsjxsb.com
newgreenarmy.com
xujingch.com
metro114.com
alibalala.com
7077f.vip
taotaoxt.com
vinuxhome.com
uerlqe.com
njjinbaixing.com
88416789.com
899792.com
daxianglx.com
abkingwl.com
chumanduo.com
ruigezx.com
40fenzhong.com
xmtesting.com
zehnnanne.com
bigdzh.com
yaichao.com
hcesc.cn
haowui.com
xaysys.com
daaali.com
zrqd5.com
xsjyun.cn
toutiao.social
oddsds.com
pch3366.com
superxq.com

!------------------------------some------------------------------
kuaidi100.com##.download-nav,.open-mp
mail.126.com##.gWel-bottom
!------------------------------bilibili------------------------------
chat.bilibili.com
hdslb.com/bfs/live
hdslb.com/bfs/static/live
xycdn.com/api/get_seeds
bilibili.com##.z-aside-area,.haruna-sekai-de-ichiban-kawaii,.haruna-sekai-de-ichiban-kawaii,.z-room-background,#sections-vm,.z-sidebar,.comment-m
!------------------------------video site------------------------------
zzyanhushi.com
wyxcb6.top
cloudpsvn.com
07622.cc
cj071.cc
feigedaojia.com
aisouk.cn
jungbey.xyz
40yb.com/js/bbs/pb.js
97kpz.com/js/bbs/pb.js
40yb.com/js/seajump.js
97kpz.com/js/seajump.js
40yb.com,60ws.com,aiaike.com,tv6.cc,980kp.com,97kpb.com,980kp.com,9zdy.com,98ju.com,97kpz.com,kp980.com,92kpb.com##.animated,div[style*="infinite"],div[style*="right: 0px;"]
97kpz.com/js/bbk/b.js
!------------------------------props------------------------------
! 40yb.com#?#:-abp-has(> canvas)
! micaitu.net,40yb.com,60ws.com,aiaike.com,tv6.cc,980kp.com,97kpb.com,980kp.com,9zdy.com#?#:-abp-properties(transform)
! micaitu.net,40yb.com,60ws.com,aiaike.com,tv6.cc,980kp.com,97kpb.com,980kp.com,9zdy.com#?#:-abp-properties(animation)
! micaitu.com,40yb.com,60ws.com,aiaike.com,tv6.cc#?#:-abp-properties(/border-right-color:.*;/)
! micaitu.com,40yb.com,60ws.com,aiaike.com,tv6.cc#?#:-abp-properties(/position:fixed;bottom:.*;/)
! End
